### ISSUE TITLE
Revisión de infraestructura en Docker

### ISSUE THREAD

**Issue by dosquisd** [ISCOUTB/AG-GestionHospitalaria#11]

**Comment by elalan86** [comment]
**Diagrama de infraestructura:**
Usuarios finales: Doctores personal administrativo, pacientes.
Aplicación de Gestión Hospitalaria (HIS):
Frontend: Interfaz web accesible desde navegadores.
Backend: gestiona la lógica del negocio y la comunicación con la base de datos.
Se usara FastAPI con una arquitectura de microservicios centrada en datos
Base de Datos: Para almacenar la información de los pacientes, camas, citas, historias clínicas.
DB Server: Almacena y consulta la información de la base de datos (SQL, NoSQL) para datos relacionales o SQL se usara
PostgresSQL y para los danos no relacionales se usaran MongoDB.
Servicios:
1. Servicio de Gestión de Usuarios
Descripción: Maneja el registro, autenticación y autorización de los usuarios (médicos, administrativos, pacientes).
Características:
-Autenticación segura .
-Gestión de roles y permisos.
2. Servicio de Gestión de Pacientes
Descripción: Administra los datos de los pacientes, incluyendo información personal, historial clínico y seguimiento médico.
Características:
-Crear, editar y eliminar registros de pacientes.
-Acceso a la historia clínica.
-Consulta de citas y tratamientos.
3. Servicio de Gestión de Camas
Descripción: Administra la ocupación de camas dentro del hospital.
Características:
-Verificación de disponibilidad.
-Asignación de camas a pacientes.
-Historial de uso de camas.
