### ISSUE TITLE
Construcción de diagrama E-R

### ISSUE THREAD

**Issue by dosquisd** [ISCOUTB/AG-GestionHospitalaria#14]
# Diagrama Entidad - Relación
## Descripción 
El diagrama E-R sirve como representación fundamental de todas las relaciones existentes entre las entidades presentes en el sistema, facilitando su desarrollo al dar claridad sobre algunas de las necesidades fundamentales del caso. 

## Criterios de aceptación
* El diagrama contiene la cardinalidad de todas las relaciones. 

* El diagrama comprende todas las entidades del sistema y sus interacciones.

**Comment by dosquisd** [comment]
[Diagrama entidad relación](https://github.com/ISCOUTB/AG-GestionHospitalaria/blob/main/docs/diagrams/ERD.pdf)

**Comment by jairoserrano** [comment]
adelante
