### ISSUE TITLE
Elección de motor de bases de datos

### ISSUE THREAD

**Issue by dosquisd** [ISCOUTB/AG-GestionHospitalaria#7]
Diferenciar elementos SQL y no SQL del proyecto, elegir el motor que se utilizará para gestionar cada uno.

**Comment by dosquisd** [comment]
Para las bases de datos SQL utilizaremos Postgres debido a su robustez, para almacenar los siguientes datos:

- Información de usuarios del sistema (pacientes, doctores y administradores).
- Información de las consultas.
- Información de las camas.
- Cantidad de admisiones y altas por día.

Para las bases de datos NoSQL utilizaremos MongoDB por su facilidad para guardar los siguientes datos:

- Registro de actividad en la API.
- Relación de los documentos médicos a los pacientes.

**Comment by jairoserrano** [comment]
adelante
